(function() {var implementors = {};
implementors['gomoku'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='gomoku/board/enum.Tile.html' title='gomoku::board::Tile'>Tile</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/board/struct.GoBoard.html' title='gomoku::board::GoBoard'>GoBoard</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/board/struct.Team.html' title='gomoku::board::Team'>Team</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='gomoku/display/console/enum.Player.html' title='gomoku::display::console::Player'>Player</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/display/struct.Console.html' title='gomoku::display::Console'>Console</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/display/mouse/struct.Mouse.html' title='gomoku::display::mouse::Mouse'>Mouse</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/ia/struct.Decision.html' title='gomoku::ia::Decision'>Decision</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='gomoku/ia/turn/enum.Turn.html' title='gomoku::ia::turn::Turn'>Turn</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='gomoku/cmd_option/struct.CmdOption.html' title='gomoku::cmd_option::CmdOption'>CmdOption</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
